### ISSUE TITLE
Migrate Ctx to Hooks

### ISSUE THREAD

**Issue by rehat101** [brigand/rearm#19]
Migrate the `Ctx` component to Hooks

**Comment by rehat101** [comment]
How can we approach this? Will the store structure stay same?

**Comment by brigand** [comment]
The store can stay the same, but it might be more convenient for subscribe to return a function that unsubscribes when called instead of a separate unsubscribe function.

Subscribing can be done in `useEffect`. In react-redux, they don't actually store the state in a useState, but rather fetch the current state while rendering. I think that would work well for us as well, so the useState/useReducer can just be a counter for the number of updates, and we can ignore the current value (this is like forceUpdate in classes).
