### ISSUE TITLE
Migrate PortalGun to hooks

### ISSUE THREAD

**Issue by nullhook** [brigand/rearm#24]
The current `PortalGun` component uses an old api. We need to migrate to hooks and spruce it.

How can we approach this?

**Comment by brigand** [comment]
The API would most directly change to this:

```js
const [Source, Dest] = usePortalGun();
```

We could keep the current PortalGun component available since it's trivial to implement with hooks (if it's worth having for the specific case of creating a PortalGun in an array.map or similar).

```js
function PortalGun({ children }) {
  const [Source, Dest] = usePortalGun();
  return children(Source, Dest);
}
```

We would construct the Source/Dest components inside a `useMemo` with an empty dependencies array. 

The inner components could be converted to function components with hooks, or we could leave them as classes (doesn't really matter either way).
